import { publicProducts } from "./products";

// The live site redirects www.uniquem.ca to the apex domain. Keep every
// canonical URL, JSON-LD URL, and sitemap entry on the preferred host.
export const origin = "https://uniquem.ca";
const products = [
  ["elixir", "Elixir Water-Based Drilling Fluid Lubricant | Uniquem", "Elixir is a concentrated biodegradable lubricant designed to improve water-based drilling fluid lubricity and help manage torque, drag and sticking tendency.", "/images/products/elixir-pallet.webp", "Elixir water-based drilling fluid lubricant"],
  ["fusion", "Fusion Rheology & Filtration Polymer | Uniquem", "Fusion is a dispersible polymer blend supporting rheology, suspension, hole cleaning and filtrate control in water-based drilling fluids.", "/images/products/fusion-pallet.webp", "Fusion rheology and filtration polymer blend"],
  ["inertia", "Inertia Interfacial-Tension Reducer | Uniquem", "Inertia is an amphiphilic oilfield treatment designed to reduce interfacial tension and capillary pressure in compatible water, oil and acid systems.", "/images/products/inertia-pallet.webp", "Inertia interfacial-tension reducer"],
  ["unicide-g15", "UniCide-G15 Oilfield Biocide | Uniquem", "UniCide-G15 is a concentrated glutaraldehyde-based oilfield biocide for broad-spectrum microbial control, including sulfate-reducing bacteria.", "/images/products/unicide-g15-pallet.webp", "UniCide-G15 broad-spectrum oilfield biocide"],
  ["unipac-hvd", "UniPAC HVD High-Viscosity PAC | Uniquem", "UniPAC HVD is a rapidly hydrating high-viscosity polyanionic cellulose for rheology and filtrate control in water-based drilling fluids.", "/images/products/unipac-hvd-pallet.webp", "UniPAC HVD high-viscosity polyanionic cellulose"],
  ["unipac-lvd", "UniPAC LVD Low-Viscosity PAC | Uniquem", "UniPAC LVD is a rapidly hydrating low-viscosity polyanionic cellulose for filtrate control with minimal added viscosity.", "/images/products/unipac-lvd-pallet.webp", "UniPAC LVD low-viscosity polyanionic cellulose"],
  ["unistop", "UniSTOP Lost-Circulation Material | Uniquem", "UniSTOP is a water-swellable synthetic polymer designed to help control severe seepage and lost circulation in high-loss wells.", "/images/products/unistop-pallet.webp", "UniSTOP water-swellable lost-circulation material"],
  ["uniq-rm", "Uniq-RM Clay-Free Invert-Emulsion System | Uniquem", "Uniq-RM is a temperature-stable, clay-free invert-emulsion drilling fluid system supporting rheology, suspension, filtration and lubricity.", "/images/products/uniq-rm-pallet.webp", "Uniq-RM clay-free invert-emulsion drilling fluid system"],
  ["unistar", "UniSTAR Filtration-Control Additive | Uniquem", "UniSTAR is a modified-starch additive supporting filtration control, encapsulation and borehole stability in water-based fluid systems.", "/images/products/unistar-pallet.webp", "UniSTAR modified-starch filtration-control additive"],
  ["zan-hd", "ZAN HD Xanthan Biopolymer | Uniquem", "ZAN HD is a highly dispersible xanthan biopolymer designed to develop low-end rheology, suspension and hole-cleaning performance.", "/images/products/zan-hd-pallet.webp", "ZAN HD highly dispersible xanthan biopolymer"],
  ["solublok", "SoluBlok Seepage-Loss Material for Oil-Based Fluids | Uniquem", "SoluBlok is a slow-dissolving, oil-absorbing particulate designed to expand and temporarily control seepage in oil-based drilling fluids.", "/images/products/solublok-pallet.webp", "SoluBlok oil-absorbing seepage-loss material"],
  ["epsealon", "EpSealon Removable Fluid-Loss Material | Uniquem", "EpSealon forms an expansive, low-permeability filter cake to help control drilling-fluid losses, with post-drilling washability for productive intervals.", "/images/products/epsealon-pallet.webp", "EpSealon removable fluid-loss material"],
  ["kaolok", "KaoloK Kaolinite Fines-Control Treatment | Uniquem", "KaoloK is a formation treatment designed to reduce kaolinite fines migration, limit pore-throat plugging and help protect near-wellbore permeability.", "/images/products/kaolok-tote.webp", "KaoloK kaolinite fines-control treatment"],
  ["sandweb", "SandWeb Sand Consolidation Chemistry | Uniquem", "SandWeb sand consolidation chemistry for hydraulic fracturing supports sand control and fracture-treatment stability as an alternative to resin-coated sand. Available in 1000 L totes.", "/images/products/sandweb-tote.webp", "SandWeb sand consolidation chemistry"],
  ["corrosion-inhibitor", "Corrosion Inhibitor for Alberta Oilfield and Pipeline Applications | Uniquem", "Uniquem corrosion inhibitor support for compatible oilfield, pipeline, production and related industrial applications, with custom formulation and blending discussions.", "/images/products/corrosion-inhibitor-tote.webp", "Corrosion Inhibitor chemical tote for oilfield and pipeline applications"],
  ["friction-reducer", "Friction Reducer for Alberta Oilfield and Pipeline Applications | Uniquem", "Uniquem friction reducer support for compatible oilfield, pipeline, production and fluid-handling applications, with custom blending and packaging options.", "/images/products/friction-reducer-tote.webp", "Friction Reducer chemical tote for oilfield and pipeline applications"]
].map(([slug, title, description, image, h1]) => ({ path: `/chemicals/${slug}`, title, description, image, h1 }));

export const routes = [
  { path: "/", title: "Advanced Oilfield Chemical Solutions | Uniquem", description: "Advanced oilfield chemical solutions for oil and gas exploration and production, shaped through research, application and environmental responsibility.", image: "/images/uniquem/oilfield-chemicals-hero-v2.webp", h1: "Chemical solutions with purpose", type: "WebPage" },
  { path: "/about-us", title: "About Uniquem | Oilfield Chemical Solutions", description: "Uniquem develops chemical solutions for oil and gas exploration and production through research, manufacturing and application.", image: "/images/uniquem/industrial-facility.png", h1: "Chemistry for oil and gas", type: "AboutPage" },
  { path: "/chemicals", title: "Drilling Fluid Systems & Specialty Additives | Uniquem", description: "Explore water-based and oil-based drilling fluid systems and specialty additives for rheology, filtration, lubricity, lost circulation and microbial control.", image: "/images/uniquem/materials-warehouse.png", h1: "Specialty chemistry with a clear purpose", type: "CollectionPage" },
  { path: "/contact-us", title: "Contact Uniquem | Oilfield Chemical Solutions", description: "Contact Uniquem in Calgary about chemical needs and challenges in oil and gas exploration and production.", image: "/images/uniquem/industrial-facility.png", h1: "Let’s discuss your chemical needs", type: "ContactPage" },
  { path: "/service-areas/alberta", title: "Alberta Oilfield Chemical Solutions | Uniquem", description: "Discuss oilfield chemical solutions, custom formulation, blending and packaging for compatible applications across Calgary, Edmonton and Alberta.", image: "/images/uniquem/industrial-facility.png", h1: "Oilfield chemical solutions across Alberta", type: "CollectionPage" },
  ...products.map((product) => ({ ...product, h1: publicProducts.find((item) => item.path === product.path)!.name, type: "Product" }))
];
const escape = (value: string) => value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
const absolute = (value: string) => `${origin}${value}`;
export type SeoRoute = (typeof routes)[number];
const organization = { "@type": "Organization", "@id": `${origin}/#organization`, name: "Uniquem", url: origin, logo: absolute("/brand/uniquem-logo-light.png"), telephone: "+14032622004", areaServed: [{ "@type": "AdministrativeArea", name: "Alberta" }, ...["Calgary", "Edmonton", "Grande Prairie", "Red Deer", "Fort McMurray", "Lethbridge", "Medicine Hat", "Lloydminster"].map((name) => ({ "@type": "City", name, containedInPlace: { "@type": "AdministrativeArea", name: "Alberta" } }))], address: { "@type": "PostalAddress", streetAddress: "#6, 7115–48 St SE", addressLocality: "Calgary", addressRegion: "AB", postalCode: "T2C 5A4", addressCountry: "CA" } };
export function jsonLd(route: SeoRoute) {
  const page = { "@type": route.type === "Product" ? "WebPage" : route.type, "@id": `${absolute(route.path)}#webpage`, url: absolute(route.path), name: route.h1, description: route.description, inLanguage: "en-CA", isPartOf: { "@id": `${origin}/#website` }, about: { "@id": `${origin}/#organization` }, primaryImageOfPage: { "@type": "ImageObject", url: absolute(route.image) } };
  const graph: object[] = [organization, { "@type": "WebSite", "@id": `${origin}/#website`, url: origin, name: "Uniquem", inLanguage: "en-CA", publisher: { "@id": `${origin}/#organization` } }, page];
  if (route.type === "Product") graph.push({ "@type": "Product", "@id": `${absolute(route.path)}#product`, name: route.h1, description: route.description, url: absolute(route.path), image: absolute(route.image), brand: { "@type": "Brand", name: "Uniquem" }, manufacturer: { "@id": `${origin}/#organization` }, category: "Oilfield chemical solution", mainEntityOfPage: { "@id": page["@id"] } });
  if (route.path !== "/") {
    const breadcrumbItems = [{ name: "Home", item: origin }, ...(route.type === "Product" ? [{ name: "Chemicals", item: absolute("/chemicals") }, { name: route.h1, item: absolute(route.path) }] : [{ name: route.h1, item: absolute(route.path) }])];
    graph.push({ "@type": "BreadcrumbList", itemListElement: breadcrumbItems.map((item, index) => ({ "@type": "ListItem", position: index + 1, ...item })) });
  }
  return JSON.stringify({ "@context": "https://schema.org", "@graph": graph }).replaceAll("<", "\\u003c");
}
export function head(route: SeoRoute) { const url = absolute(route.path); return `<title>${escape(route.title)}</title><meta name="description" content="${escape(route.description)}"><meta name="robots" content="index, follow, max-image-preview:large"><link rel="canonical" href="${url}"><meta property="og:type" content="${route.type === "Product" ? "product" : "website"}"><meta property="og:title" content="${escape(route.title)}"><meta property="og:description" content="${escape(route.description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${absolute(route.image)}"><meta property="og:image:alt" content="${escape(route.h1)}"><meta property="og:site_name" content="Uniquem"><meta property="og:locale" content="en_CA"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escape(route.title)}"><meta name="twitter:description" content="${escape(route.description)}"><meta name="twitter:image" content="${absolute(route.image)}"><script type="application/ld+json" data-seo-jsonld>${jsonLd(route)}</script>`; }

export const seoSelectors = 'title, meta[name="description"], meta[name="robots"], link[rel="canonical"], meta[property^="og:"], meta[name^="twitter:"], script[data-seo-jsonld]';
