/* eslint-disable react-hooks/preserve-manual-memoization */
import { Line } from "@react-three/drei";
import { Canvas, useFrame } from "@react-three/fiber";
import { Suspense, useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";

function supportsWebGL() { try { const canvas = document.createElement("canvas"); return Boolean(canvas.getContext("webgl2") || canvas.getContext("webgl")); } catch { return false; } }
function useSceneState(root: React.RefObject<HTMLDivElement | null>) { const [active, setActive] = useState(true), [compact, setCompact] = useState(false), [reduced, setReduced] = useState(false), [webgl, setWebgl] = useState(true); useEffect(() => { const motion = matchMedia("(prefers-reduced-motion: reduce)"), mobile = matchMedia("(max-width: 760px)"), sync = () => { setReduced(motion.matches); setCompact(mobile.matches); setWebgl(supportsWebGL()); }; sync(); motion.addEventListener("change", sync); mobile.addEventListener("change", sync); return () => { motion.removeEventListener("change", sync); mobile.removeEventListener("change", sync); }; }, []); useEffect(() => { const element = root.current; if (!element) return; const observer = new IntersectionObserver(([entry]) => setActive(entry.isIntersecting), { rootMargin: "160px" }); observer.observe(element); return () => observer.disconnect(); }, [root]); return { active, compact, reduced, webgl }; }
function Well({ active, compact }: { active: boolean; compact: boolean }) { const group = useRef<THREE.Group>(null), points = useRef<THREE.Points>(null), curve = useMemo(() => new THREE.CatmullRomCurve3([new THREE.Vector3(-4, 12, 0), new THREE.Vector3(-4, 2, 0), new THREE.Vector3(-4, -8, 0), new THREE.Vector3(-1, -15, 0), new THREE.Vector3(6, -19, 0), new THREE.Vector3(20, -19, 0)]), []), tube = useMemo(() => new THREE.TubeGeometry(curve, compact ? 90 : 150, .72, compact ? 10 : 16, false), [curve, compact]), line = useMemo(() => curve.getPoints(compact ? 90 : 150), [curve, compact]), positions = useMemo(() => new Float32Array((compact ? 38 : 76) * 3), [compact]); useFrame(({ camera, clock }) => { if (!active) return; const t = .1 + ((Math.sin(clock.elapsedTime * .18) + 1) / 2) * .78, target = curve.getPointAt(t); camera.position.lerp(target.clone().add(new THREE.Vector3(compact ? 7 : 10, compact ? 4 : 5, compact ? 15 : 20)), .025); camera.lookAt(target); if (group.current) group.current.rotation.y = Math.sin(clock.elapsedTime * .1) * .06; if (!points.current) return; const values = points.current.geometry.attributes.position.array as Float32Array, count = values.length / 3; for (let i = 0; i < count; i++) { const point = curve.getPointAt((i / count + clock.elapsedTime * .05) % 1); values[i * 3] = point.x; values[i * 3 + 1] = point.y; values[i * 3 + 2] = point.z; } points.current.geometry.attributes.position.needsUpdate = true; }); return <group ref={group}><mesh geometry={tube}><meshPhysicalMaterial color="#19cbb0" transparent opacity={.25} roughness={.2} metalness={.12} transmission={.2} depthWrite={false} side={THREE.DoubleSide} /></mesh><Line points={line} color="#8effe8" lineWidth={compact ? 1.4 : 2.4} transparent opacity={.7} /><points ref={points}><bufferGeometry><bufferAttribute attach="attributes-position" args={[positions, 3]} /></bufferGeometry><pointsMaterial color="#d5fff6" size={compact ? .22 : .3} transparent opacity={.9} depthWrite={false} /></points><gridHelper args={[90, 45, "#1a8992", "#0b4b56"]} position={[8, 12, 0]} /></group>; }
function Signal({ active, compact }: { active: boolean; compact: boolean }) { const paths = useMemo(() => [[[-13, 0, 7], [-6, 1, 3], [0, .4, 0]], [[13, 0, 7], [6, 1.4, 3], [0, .4, 0]], [[-10, 0, -9], [-4, 1, -4], [0, .4, 0]], [[11, 0, -8], [5, 1.1, -3], [0, .4, 0]]].map((path) => new THREE.CatmullRomCurve3(path.map(([x, y, z]) => new THREE.Vector3(x, y, z)))), []), points = useRef<THREE.Points>(null), positions = useMemo(() => new Float32Array((compact ? 32 : 64) * 3), [compact]); useFrame(({ camera, clock }) => { if (!active) return; camera.position.lerp(new THREE.Vector3(Math.sin(clock.elapsedTime * .1) * (compact ? 2 : 4), compact ? 9 : 8, compact ? 16 : 20), .02); camera.lookAt(0, 0, 0); if (!points.current) return; const values = points.current.geometry.attributes.position.array as Float32Array, count = values.length / 3; for (let i = 0; i < count; i++) { const point = paths[i % paths.length].getPointAt((i / count * 2.4 + clock.elapsedTime * .1) % 1); values[i * 3] = point.x; values[i * 3 + 1] = point.y; values[i * 3 + 2] = point.z; } points.current.geometry.attributes.position.needsUpdate = true; }); return <group><gridHelper args={[65, compact ? 30 : 48, "#1596a0", "#0a4b58"]} position={[0, -.1, 0]} />{paths.map((path, i) => <Line key={i} points={path.getPoints(compact ? 28 : 58)} color={i % 2 ? "#32c9ed" : "#1ce7be"} lineWidth={compact ? 1.1 : 1.7} transparent opacity={.7} />)}<mesh><sphereGeometry args={[compact ? .22 : .3, 20, 20]} /><meshStandardMaterial color="#d8fff6" emissive="#1ce7be" emissiveIntensity={3} /></mesh><points ref={points}><bufferGeometry><bufferAttribute attach="attributes-position" args={[positions, 3]} /></bufferGeometry><pointsMaterial color="#c5fff3" size={compact ? .17 : .24} transparent opacity={.95} /></points></group>; }
function Scene({ kind, active, compact }: { kind: "well" | "signal"; active: boolean; compact: boolean }) { return <Canvas frameloop={active ? "always" : "demand"} dpr={[1, compact ? 1.1 : 1.5]} camera={{ position: [8, 5, 18], fov: 46 }} gl={{ antialias: !compact, alpha: true, powerPreference: "high-performance" }}><fog attach="fog" args={["#041923", 20, 80]} /><ambientLight intensity={1.5} /><directionalLight position={[12, 16, 13]} intensity={2.5} color="#e0fffa" /><pointLight position={[-4, 2, 5]} intensity={22} color="#1ce7be" distance={38} /><Suspense fallback={null}>{kind === "well" ? <Well active={active} compact={compact} /> : <Signal active={active} compact={compact} />}</Suspense></Canvas>; }
export default function UniquemScene({ kind = "well", fallback = "/images/technology-3d.png" }: { kind?: "well" | "signal"; fallback?: string }) { const root = useRef<HTMLDivElement>(null), { active, compact, reduced, webgl } = useSceneState(root); return <div className="scene-shell" ref={root} aria-hidden="true">{!reduced && webgl ? <Scene kind={kind} active={active} compact={compact} /> : <img src={fallback} alt="" />}</div>; }
