import { RoundedBox } from "@react-three/drei";
import { Canvas, useFrame } from "@react-three/fiber";
import { Suspense, useEffect, useMemo, useRef, useState } from "react";
import * as THREE from "three";

function supportsWebGL() { try { const canvas = document.createElement("canvas"); return Boolean(canvas.getContext("webgl2") || canvas.getContext("webgl")); } catch { return false; } }
function useSceneState(root: React.RefObject<HTMLDivElement | null>) { const [active, setActive] = useState(true), [compact, setCompact] = useState(false), [reduced, setReduced] = useState(false), [webgl, setWebgl] = useState(true); useEffect(() => { const motion = matchMedia("(prefers-reduced-motion: reduce)"), mobile = matchMedia("(max-width: 760px)"), sync = () => { setReduced(motion.matches); setCompact(mobile.matches); setWebgl(supportsWebGL()); }; sync(); motion.addEventListener("change", sync); mobile.addEventListener("change", sync); return () => { motion.removeEventListener("change", sync); mobile.removeEventListener("change", sync); }; }, []); useEffect(() => { const element = root.current; if (!element) return; const observer = new IntersectionObserver(([entry]) => setActive(entry.isIntersecting), { rootMargin: "160px" }); observer.observe(element); return () => observer.disconnect(); }, [root]); return { active, compact, reduced, webgl }; }
function Pallet() { const bagColors = ["#dce7e5", "#f0f3ee", "#b9d3d0", "#e6ece4", "#c8dcda", "#eef0e7"]; return <group position={[0, -3.5, 0]} rotation={[0, -.18, 0]}><mesh position={[0, -.18, 0]}><boxGeometry args={[6.8, .36, 4.2]} /><meshStandardMaterial color="#8b5b3e" roughness={.88} /></mesh>{[-1.9, 0, 1.9].map((x) => <mesh key={x} position={[x, .08, 0]}><boxGeometry args={[.24, .82, 4.05]} /><meshStandardMaterial color="#b8794e" roughness={.9} /></mesh>)}{[-1.55, 0, 1.55].map((z) => <mesh key={z} position={[0, .08, z]}><boxGeometry args={[6.5, .82, .24]} /><meshStandardMaterial color="#9e6847" roughness={.9} /></mesh>)}{bagColors.map((color, index) => { const x = (index % 3 - 1) * 2.05, z = (Math.floor(index / 3) - .5) * 1.45; return <group key={index} position={[x, 1.15, z]}><RoundedBox args={[1.7, 1.95, 1.15]} radius={.13} smoothness={3}><meshPhysicalMaterial color={color} roughness={.48} metalness={.04} clearcoat={.25} /></RoundedBox><mesh position={[0, .08, .59]}><boxGeometry args={[1.32, .025, .015]} /><meshBasicMaterial color={index % 2 ? "#62b8ad" : "#194f5a"} transparent opacity={.6} /></mesh><mesh position={[0, -.22, .59]}><boxGeometry args={[.9, .018, .015]} /><meshBasicMaterial color="#6a8688" transparent opacity={.38} /></mesh></group>; })}</group>; }
function Chemistry({ active, compact }: { active: boolean; compact: boolean }) { const bubbles = useRef<THREE.Group>(null), count = compact ? 28 : 52, bubbleData = useMemo(() => Array.from({ length: count }, (_, index) => ({ x: (Math.sin(index * 5.3) * 2.1), y: -2.5 + (index % 9) * .62, z: (Math.cos(index * 4.1) * 1.7), scale: .06 + (index % 4) * .035 })), [count]); useFrame(({ camera, clock }) => { if (!active) return; camera.position.lerp(new THREE.Vector3(compact ? 8.2 : 9.5, compact ? 3.6 : 4.8, compact ? 14 : 17), .025); camera.lookAt(0, -.8, 0); if (bubbles.current) bubbles.current.children.forEach((bubble, index) => { const item = bubbleData[index]; bubble.position.y = item.y + ((clock.elapsedTime * (.08 + (index % 3) * .015)) % 1.1); bubble.position.x = item.x + Math.sin(clock.elapsedTime * .28 + index) * .08; }); }); return <group><Pallet /><group ref={bubbles}>{bubbleData.map((item, index) => <mesh key={index} position={[item.x, item.y, item.z]} scale={item.scale}><sphereGeometry args={[1, 12, 12]} /><meshPhysicalMaterial color="#baffef" transparent opacity={.64} transmission={.35} roughness={.08} /></mesh>)}</group><mesh position={[0, -1.2, -.45]}><cylinderGeometry args={[3.1, 3.1, 5.8, compact ? 32 : 48, 1, true]} /><meshPhysicalMaterial color="#42d7c0" transparent opacity={.08} roughness={.08} transmission={.65} side={THREE.DoubleSide} depthWrite={false} /></mesh><mesh position={[0, 1.65, -.45]}><torusGeometry args={[3.1, .045, 10, 48]} /><meshBasicMaterial color="#baffef" transparent opacity={.5} /></mesh><gridHelper args={[45, 30, "#1a8992", "#0b4b56"]} position={[0, -3.75, 0]} /></group>; }
function Scene({ active, compact }: { active: boolean; compact: boolean }) { return <Canvas frameloop={active ? "always" : "demand"} dpr={[1, compact ? 1.08 : 1.45]} camera={{ position: [9, 4.8, 17], fov: 45 }} gl={{ antialias: !compact, alpha: true, powerPreference: "high-performance" }}><fog attach="fog" args={["#041923", 14, 48]} /><ambientLight intensity={1.4} /><directionalLight position={[8, 14, 10]} intensity={3} color="#e4fffa" /><pointLight position={[-3, 4, 4]} intensity={24} distance={30} color="#1ce7be" /><Suspense fallback={null}><Chemistry active={active} compact={compact} /></Suspense></Canvas>; }
export default function UniquemScene({ fallback = "/images/uniquem/industrial-facility.png" }: { fallback?: string }) { const root = useRef<HTMLDivElement>(null), { active, compact, reduced, webgl } = useSceneState(root); return <div className="scene-shell" ref={root} aria-hidden="true">{!reduced && webgl ? <Scene active={active} compact={compact} /> : <img src={fallback} alt="" />}</div>; }
